# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coding Standards
email: info@patoliyainfotech.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "https://patoliyainfotech.github.io"
twitter_username: patoliyatech
github_username:  patoliyainfotech
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
- ubuntu
- html
- css
- javascript
- jquery
- typescript
- angularjs
- reactjs
- nextjs
- vuejs
- nodejs
- php
- laravel
- database
# - android
# - react_native
- qa
- seo
- git
- software_installation
- aws_third_party_integration
- ai_coding

coding_pages:
  -
    title: "Ubuntu"
    png: "ubuntu"
    description: ""
    permalink: "/assets/pdf/ubuntu.pdf"
  -
    title: "HTML"
    png: "html"
    description: ""
    permalink: "/assets/pdf/html.pdf"
  -
    title: "CSS"
    png: "css"
    description: ""
    permalink: "/assets/pdf/css.pdf"
  -
    title: "Javascript"
    png: "javascript"
    description: ""
    permalink: "/assets/pdf/javascript.pdf"
  -
    title: "jQuery"
    png: "jquery"
    description: ""
    permalink: "/assets/pdf/jquery.pdf"
  -
    title: "TypeScript"
    png: "typescript"
    description: ""
    permalink: "/assets/pdf/typescript.pdf"
  -
    title: "AngularJs"
    png: "angularjs"
    description: ""
    permalink: "/assets/pdf/angularjs.pdf"
  -
    title: "ReactJs"
    png: "reactjs"
    description: ""
    permalink: "/assets/pdf/reactjs.pdf"
  -
    title: "NextJs"
    png: "nextjs"
    description: ""
    permalink: "/assets/pdf/nextjs.pdf"
  -
    title: "VueJs"
    png: "vuejs"
    description: ""
    permalink: "/assets/pdf/vuejs.pdf"
  -
    title: "NodeJs"
    png: "nodejs"
    description: ""
    permalink: "/assets/pdf/nodejs.pdf"
  -
    title: "PHP"
    png: "php"
    description: ""
    permalink: "/assets/pdf/php.pdf"
  -
    title: "Laravel"
    png: "laravel"
    description: ""
    permalink: "/assets/pdf/laravel.pdf"
  -
    title: "DataBase"
    png: "database"
    description: ""
    permalink: "/database"
  -
    title: "QA"
    png: "qa"
    description: ""
    permalink: "/assets/pdf/qa.pdf"
  -
    title: "SEO"
    png: "seo"
    description: ""
    permalink: "/assets/pdf/seo.pdf"
  -
    title: "Git"
    png: "github"
    description: ""
    permalink: "/assets/pdf/git.pdf"
  -
    title: "Software installation"
    png: "software-installation"
    description: ""
    permalink: "https://github.com/PatoliyaInfotech/quick-setup/tree/master/ubuntu/22-ubuntu"
  -
    title: "AWS & Third party Integration"
    png: "aws_third_party"
    description: ""
    permalink: "/assets/pdf/aws_third_party_integration.pdf"
  -
    title: "AI powered coding"
    png: "ai_coding"
    description: ""
    permalink: "/assets/pdf/ai_coding.pdf"

